CREATE TABLE [dbo].[PhotoAlbum]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [RowId] UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE DEFAULT NEWSEQUENTIALID(), 
    [Description] NVARCHAR(MAX) NULL, 
    [Photo] VARBINARY(MAX) FILESTREAM DEFAULT(0x)
)
